name: dr-aids
services:
  app:
    build:
      context: .            # ✅ 현재 폴더(~/app/BE)를 빌드 컨텍스트로
      dockerfile: Dockerfile
    container_name: dr-aids-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    # ⬇️ 앱에서 환경변수를 직접 읽도록 했으면 그대로 두고,
    # application.yml이 SPRING_DATASOURCE_URL을 기대한다면 아래처럼 한 줄로 넘기는 게 편함.
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:${DB_PORT:-3306}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}

    # ⚠️ 기본 JRE 이미지는 wget/curl이 없음 → 헬스체크 실패 원인
    # 아래 healthcheck를 쓰려면 Dockerfile에서 curl 설치 필요(예시: apt-get install -y curl)
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsS http://localhost:8080/actuator/health || exit 1"]
    #   interval: 15s
    #   timeout: 3s
    #   retries: 5
