name: dr-aids
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dr-aids-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      -  /etc/dr-aids/app.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:${DB_PORT:-3306}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}
